/**
 * @class
 * @extends Language
 */
class Lithuania extends Language
{
    /**
     * @return {Map}
     * @method
     * @public
     */
    createMapping ()
    {
        return new Map([
            ["{{書き出し先の選択}}", "Eksporto paskirties vietos pasirinkimas"],
            ["{{画質}}", "vaizdo kokybė (filmas, vaizdo įrašas ir t. t.)"],
            ["{{座標}}", "koordinatės"],
            ["{{MovieClipを編集}}", "Redaguoti \"MovieClip\"."],
            ["{{親の階層へ移動}}", "Perkelti į pirminę hierarchiją"],
            ["{{ロックされたレイヤーです}}", "Užrakintas sluoksnis."],
            ["{{トゥイーンには複数のオブジェクトを設置できません}}", "Keli objektai negali būti patalpinti ant tween."],
            ["{{名前が重複しています}}", "Dubliuojasi pavadinimai."],
            ["{{名前は必須です}}", "Reikalingas vardas."],
            ["{{基準点}}", "atskaitos taškas"],
            ["{{自由変形ツール}}", "Nemokamas transformavimo įrankis"],
            ["{{キーフレームに変換}}", "Konvertuota į raktinius kadrus"],
            ["{{空のキーフレームに変換}}", "Konvertuojama į tuščius raktinius kadrus."],
            ["{{最初のフレームに移動}}", "Pereikite prie pirmojo kadro"],
            ["{{最後のフレームに移動}}", "Pereiti į paskutinį kadrą"],
            ["{{SWFを解析中}}", "Analizuojami SWF."],
            ["{{JSONを生成}}", "Generuoti JSON"],
            ["{{ファイルを生成}}", "Sukurti failą"],
            ["{{N2Dファイルの読み込み}}", "N2D failų įkėlimas."],
            ["{{JSONの読み込み}}", "JSON skaitymas."],
            ["{{データを解凍中}}", "Išpakuojami duomenys."],
            ["{{データを圧縮中}}", "Duomenų suspaudimas."],
            ["{{エンコード}}", "koduoti"],
            ["{{外部ファイルの読み込み}}", "Išorinių failų įkėlimas"],
            ["{{バイナリデータを生成}}", "Generuoti dvejetainius duomenis."],
            ["{{データベースを起動}}", "Duomenų bazės paleidimas"],
            ["{{データを保存中}}", "Duomenų saugojimas."],
            ["{{完了}}", "užbaigimas"],
            ["{{ステージ左揃え}}", "derinimas kairėje pusėje"],
            ["{{ステージ中央揃え(水平方向)}}", "Scenos centras (horizontalus)"],
            ["{{ステージ右揃え}}", "Scenos dešinės pusės derinimas"],
            ["{{ステージ上揃え}}", "pasirodymas scenoje"],
            ["{{ステージ中央揃え(垂直方向)}}", "Scenos centravimas (vertikalus)"],
            ["{{ステージ下揃え}}", "pagrindimas"],
            ["{{定規}}", "(matavimo) liniuotė"],
            ["{{表示}}", "rodyti"],
            ["{{ショートカット}}", "spartusis klavišas"],
            ["{{レイヤーを複製}}", "Dubliuoti sluoksnį"],
            ["{{未使用のフォルダを削除}}", "Ištrinkite nenaudojamus aplankus."],
            ["{{同名のアイテムが存在します}}", "Yra to paties pavadinimo elementas (-ai)."],
            ["{{追加ファイル}}", "papildomas failas"],
            ["{{既存のコンテンツ}}", "Esamas turinys."],
            ["{{上書きするか、ファイル名を変更して追加するか、スキップを選択する事ができます}}", "Galite pasirinkti perrašyti, pervadinti ir pridėti failus arba praleisti"],
            ["{{全て上書き}}", "Perrašyti visus"],
            ["{{全てスキップ}}", "Praleisti visus."],
            ["{{追加・上書き}}", "Papildymai ir perrašymai"],
            ["{{スキップ}}", "praleisti"],
            ["{{表示確認したいフレームを指定}}", "Nurodykite rėmelį, kurio rodinį norite patikrinti."],
            ["{{ファイル名を指定}}", "Nurodykite failo pavadinimą"],
            ["{{ファイル名}}", "failo pavadinimas"],
            ["{{終了フレームを指定}}", "Nurodykite galinį rėmelį"],
            ["{{開始フレームを指定}}", "Nurodykite pradžios rėmelį"],
            ["{{フレーム設定}}", "rėmo nustatymas"],
            ["{{書き出し設定}}", "Eksporto nustatymai"],
            ["{{ファイル形式の選択}}", "Failo formato pasirinkimas"],
            ["{{ファイル形式}}", "failo formatas"],
            ["{{サイズ設定}}", "Dydžio nustatymas"],
            ["{{左上}}", "kairė-viršutinė"],
            ["{{中央上}}", "centras-viršutinis"],
            ["{{右上}}", "Dešinysis-viršutinis"],
            ["{{中央左}}", "kairiojo centro"],
            ["{{中央}}", "centrinis"],
            ["{{中央右}}", "centro dešinės"],
            ["{{左下}}", "apačioje kairėje"],
            ["{{中央下}}", "žemesnio vidurkio (pvz., klasėje)"],
            ["{{右下}}", "Dešinysis apatinis"],
            ["{{中心点のX座標}}", "centro taško X koordinatė"],
            ["{{中心点のY座標}}", "centro taško Y koordinatė"],
            ["{{MovieClipに変換}}", "Konvertuoti į MovieClip"],
            ["{{変換}}", "transformacija"],
            ["{{ループ回数}}", "Kilpų skaičius"],
            ["{{カーブポインターの削除}}", "Ištrinkite kreivės rodyklę."],
            ["{{ステージ基準}}", "Etapo kriterijai"],
            ["{{閉じる}}", "arti (pvz., knyga, akys, susitikimas ir pan.)"],
            ["{{保存}}", "saugykla (paprastai skysta, pvz., lietaus vanduo, arba už užtvankos)."],
            ["{{リセット}}", "iš naujo nustatyti"],
            ["{{スクリーン}}", "ekranas"],
            ["{{ショートカット設定}}", "Spartieji nustatymai"],
            ["{{レイヤーカラー}}", "sluoksniuota spalva (spalva)"],
            ["{{Next2Dを支援する}}", "Palaikykite \"Next2D\"."],
            ["{{サポート}}", "parama"],
            ["{{未使用のアイテムを削除}}", "Pašalinti nenaudojamus elementus"],
            ["{{レイヤーをペースト}}", "Pastos sluoksnis."],
            ["{{レイヤーをコピー}}", "Kopijuoti sluoksnį"],
            ["{{フレームをペースト}}", "Įklijuokite rėmelį."],
            ["{{フレームをコピー}}", "Kopijavimo rėmelis."],
            ["{{キーフレームを削除}}", "Ištrinkite raktinius kadrus."],
            ["{{キーフレームに空のキーフレームを追加できません}}", "Negalima pridėti tuščių raktinių kadrų prie raktinių kadrų"],
            ["{{ズームツール}}", "Padidinimo įrankis"],
            ["{{タイムライン幅の拡大・縮小}}", "Laiko juostos pločio didinimas ir mažinimas"],
            ["{{ガイドレイヤー}}", "kreipiamasis sluoksnis"],
            ["{{音量設定}}", "Garsumo nustatymas"],
            ["{{サウンドを削除}}", "Pašalinti garsą."],
            ["{{カスタムループ}}", "pritaikyta kilpa"],
            ["{{読込のみ}}", "Tik skaityti"],
            ["{{書込を許可}}", "pašto leidimas"],
            ["{{単一行}}", "paprasta linija"],
            ["{{複数行}}", "kelių eilučių (pvz., komanda)"],
            ["{{自動で折り返し}}", "Automatinis apsisukimas"],
            ["{{左寄せ}}", "kairiuoju lygiu"],
            ["{{中央揃え}}", "centravimas"],
            ["{{右寄せ}}", "dešinėje sulygiuotas"],
            ["{{放射状グラデーション}}", "radialinė gradacija"],
            ["{{線形グラデーション}}", "linijinis gradientas"],
            ["{{画像}}", "Vaizdas."],
            ["{{画像選択}}", "Vaizdų pasirinkimas"],
            ["{{種別}}", "klasifikacija"],
            ["{{Shapeの色設定}}", "Formos spalvos nustatymai"],
            ["{{変形}}", "deformacija"],
            ["{{カラー効果}}", "spalvų efektas"],
            ["{{フィルター}}", "filtras (pvz., fotoaparato)"],
            ["{{Shapeを複製}}", "Dubliuoti formą."],
            ["{{読み込み}}", "skaityti"],
            ["{{新規フォルダー}}", "Naujas aplankas"],
            ["{{新規MovieClip}}", "Naujas filmo klipas."],
            ["{{枠に合わせてテキストをリサイズ}}", "Pakeiskite teksto dydį, kad jis tilptų į rėmelį."],
            ["{{テキストに合わせて枠をリサイズ}}", "Pakeiskite rėmelio dydį, kad jame tilptų tekstas."],
            ["{{リサイズしない}}", "Nėra dydžio keitimo"],
            ["{{フォント}}", "šriftas"],
            ["{{テキスト}}", "Tekstas."],
            ["{{ループ}}", "kilpa"],
            ["{{音量}}", "garsumas (garsas)"],
            ["{{ビデオ}}", "Vaizdo įrašas."],
            ["{{イージング}}", "palengvinimas"],
            ["{{サウンド}}", "garsas"],
            ["{{シンボル}}", "simbolis"],
            ["{{名前}}", "Vardas ir pavardė."],
            ["{{オブジェクト}}", "objektas"],
            ["{{ステージ設定}}", "Scenografija"],
            ["{{プレビュー}}", "peržiūra"],
            ["{{削除}}", "ištrynimas"],
            ["{{ペースト}}", "įklijuokite"],
            ["{{コピー}}", "kopijuoti"],
            ["{{プラグインメニュー}}", "Įskiepių meniu"],
            ["{{トゥイーン}}", "tarp"],
            ["{{カーブポインターの追加}}", "Papildoma kreivės rodyklė."],
            ["{{パスの結合}}", "Kelių sujungimas"],
            ["{{シェイプ}}", "forma"],
            ["{{キーフレームに配分}}", "Priskyrimas raktiniams kadrams"],
            ["{{レイヤーに配分}}", "Priskyrimas sluoksniams"],
            ["{{タイムライン}}", "laiko juosta"],
            ["{{整列}}", "derinimas"],
            ["{{最背面}}", "naujausias"],
            ["{{ひとつ背面へ}}", "Vienas iš jų yra gale."],
            ["{{ひとつ前面へ}}", "Vienas į priekį."],
            ["{{最前面}}", "svarbiausias"],
            ["{{重ね順}}", "(superpozicijos) tvarka"],
            ["{{プラグイン}}", "papildinys (programinė įranga)"],
            ["{{ライブラリ}}", "biblioteka"],
            ["{{プロパティ}}", "nuosavybė"],
            ["{{マスクレイヤー}}", "kaukės sluoksnis"],
            ["{{通常レイヤー}}", "Normalus sluoksnis"],
            ["{{モーショントゥイーンの削除}}", "Judesio porūšių pašalinimas."],
            ["{{モーショントゥイーンの追加}}", "Papildomi judesio dvyniai."],
            ["{{モーダル表示}}", "modalinė indikacija"],
            ["{{言語}}", "Kalba."],
            ["{{フォーマット}}", "(kompiuterio) formatas"],
            ["{{含める}}", "įtraukti (niuansas)"],
            ["{{含めない}}", "neįtraukti"],
            ["{{使い方、リファレンス}}", "Naudojimas, nuoroda."],
            ["{{非表示レイヤー}}", "paslėptas sluoksnis"],
            ["{{設定}}", "nustatymas (kompiuterio, failo ir pan.)"],
            ["{{デフォルトのループを利用する}}", "Naudokite numatytąją kilpą."],
            ["{{フレームピッカー}}", "rėmo rinktuvas"],
            ["{{左揃え}}", "kairysis pagrindimas"],
            ["{{中央揃え(水平方向)}}", "Centruotas (horizontalus)"],
            ["{{右揃え}}", "teisingas pagrindimas"],
            ["{{上揃え}}", "pagrindimas"],
            ["{{中央揃え(垂直方向)}}", "Centruotas (vertikalus)"],
            ["{{下揃え}}", "pagrindimas"],
            ["{{開始フレーム}}", "pradžios rėmas"],
            ["{{終了フレーム}}", "Galinis rėmas"],
            ["{{ループで再生}}", "Groti pagal kilpą"],
            ["{{1回再生}}", "1 atkūrimas"],
            ["{{指定したフレームで固定}}", "Fiksuojama nurodytame rėmelyje."],
            ["{{1回逆再生}}", "1 atvirkštinis atkūrimas"],
            ["{{逆ループで再生}}", "Atkūrimas atvirkštine kilpa."],
            ["{{画面の拡大・縮小}}", "Ekrano priartinimas ir atitolinimas"],
            ["{{カスタムイージングデータを保存}}", "Įrašykite pasirinktinio palengvinimo duomenis."],
            ["{{カスタムイージングデータの読込}}", "Pasirinktinio palengvinimo duomenų skaitymas."],
            ["{{プレビューのON/OFF}}", "Peržiūros įjungimas / išjungimas."],
            ["{{フォント枠サイズ}}", "šrifto rėmelio dydis"],
            ["{{フォント枠カラー}}", "Šrifto rėmelio spalva"],
            ["{{オニオンスキン}}", "svogūnų lukštai"],
            ["{{バケツツール}}", "Kibiriniai įrankiai"],
            ["{{ペンツール}}", "rašiklio įrankis"],
            ["{{ダブルクリックでカーブポイントが追加されます}}", "Dukart spustelėkite, kad pridėtumėte kreivės tašką"],
            ["{{選択ツール}}", "atrankos įrankis"],
            ["{{Shape変形ツール}}", "Formos deformacijos įrankiai"],
            ["{{テキストツール}}", "teksto įrankis"],
            ["{{矩形ツール}}", "Stačiakampio įrankis"],
            ["{{楕円ツール}}", "Elipsiniai įrankiai"],
            ["{{角丸矩形ツール}}", "Užapvalinto stačiakampio kampų įrankis"],
            ["{{塗りのカラー}}", "Dažų spalva"],
            ["{{線のカラー}}", "Linijos spalva"],
            ["{{線の太さ}}", "linijos storis"],
            ["{{プロジェクトデータの読込}}", "Projekto duomenų skaitymas"],
            ["{{プロジェクトデータを保存}}", "Išsaugoti projekto duomenis."],
            ["{{書き出し}}", "įžanginis sakinys arba pastraipa"],
            ["{{Discordへ移動}}", "Eikite į \"Discord"],
            ["{{バグ報告}}", "pranešimas apie klaidą"],
            ["{{設定}}", "nustatymas (kompiuterio, failo ir pan.)"],
            ["{{タブを追加}}", "Pridėti skirtuką."],
            ["{{タブの一覧を表示・移動}}", "Skirtukų sąrašo rodymas ir perkėlimas"],
            ["{{スクリプトを追加}}", "Pridėti scenarijų."],
            ["{{キーフレームを追加}}", "Pridėti raktinius kadrus."],
            ["{{空のキーフレームを追加}}", "Pridėkite tuščių raktinių kadrų."],
            ["{{フレームを追加}}", "Pridėti rėmelį."],
            ["{{フレームを削除}}", "Išimkite rėmą."],
            ["{{再生}}", "regeneracija"],
            ["{{停止}}", "muzikos, šokių ir kt. sustabdymas kaip gedulo ženklas."],
            ["{{ループ設定}}", "Kilpos nustatymai"],
            ["{{レイヤーを追加}}", "Pridėti sluoksnį."],
            ["{{レイヤーを削除}}", "Ištrinkite sluoksnį."],
            ["{{全てのレイヤーをハイライト}}", "Paryškinkite visus sluoksnius"],
            ["{{全てのレイヤーを非表示}}", "Paslėpti visus sluoksnius"],
            ["{{全てのレイヤーをロック}}", "Užrakinkite visus sluoksnius."],
            ["{{比率を固定}}", "Fiksuotas santykis"],
            ["{{ステージの幅}}", "Scenos plotis"],
            ["{{背景色}}", "fono spalva"],
            ["{{ステージの高さ}}", "Scenos aukštis."],
            ["{{フレームレート}}", "kadrų dažnis"],
            ["{{シンボル名}}", "simbolio pavadinimas"],
            ["{{イージング設定}}", "Lengvesnis nustatymas"],
            ["{{ビデオの音量設定}}", "Vaizdo įrašų garsumo nustatymai"],
            ["{{自動再生}}", "automatinis paleidimas"],
            ["{{テキストエリアのボーダー設定}}", "Teksto sričių ribų nustatymai."],
            ["{{テキスト入力設定}}", "teksto įvedimo nustatymas"],
            ["{{フォント選択}}", "Šrifto pasirinkimas"],
            ["{{自動サイズ調整}}", "Automatinis dydžio keitimas"],
            ["{{フォントスタイルタイプ}}", "šrifto stiliaus tipas"],
            ["{{行揃え}}", "pateisinti"],
            ["{{改行設定}}", "eilutės pertraukos nustatymas"],
            ["{{スクロール設定}}", "Slinkimo nustatymai"],
            ["{{フォントサイズ}}", "šrifto dydis"],
            ["{{フォントカラー}}", "šrifto spalva"],
            ["{{行間}}", "tarp eilučių"],
            ["{{文字幅}}", "simbolių plotis"],
            ["{{左マージン}}", "kairioji paraštė"],
            ["{{右マージン}}", "dešinioji paraštė"],
            ["{{カラー種別の選択}}", "Pasirinkite spalvos tipą"],
            ["{{背景画像の選択}}", "Fono vaizdo pasirinkimas"],
            ["{{カラーポインターを追加}}", "Papildoma spalvų rodyklė."],
            ["{{カラー値}}", "spalvos vertė"],
            ["{{アルファ(0%-100%)}}", "Alfa (0%-100%)"],
            ["{{アルファ値}}", "alfa reikšmė"],
            ["{{選択対象の幅}}", "Atrankos tikslo plotis"],
            ["{{選択対象のX座標}}", "Atrankos tikslo X koordinatė"],
            ["{{選択対象の高さ}}", "Atrankos tikslo aukštis"],
            ["{{選択対象のY座標}}", "Atrankos tikslo Y koordinatė"],
            ["{{選択対象の幅の伸縮}}", "Pasirinkimo taikinio pločio didinimas ir mažinimas"],
            ["{{選択対象を回転}}", "Pasirinkimo pasukimas"],
            ["{{選択対象の高さの伸縮}}", "Atrankos taikinio aukščio didinimas ir mažinimas."],
            ["{{アルファオフセット(-255〜255)}}", "Alfa poslinkis (nuo -255 iki 255)"],
            ["{{赤(0%-100%)}}", "Raudona (0-100 %)"],
            ["{{赤オフセット(-255〜255)}}", "Raudonos spalvos poslinkis (nuo -255 iki 255)"],
            ["{{緑(0%-100%)}}", "Žalia (0-100 %)"],
            ["{{緑オフセット(-255〜255)}}", "Žalios spalvos poslinkis (nuo -255 iki 255)"],
            ["{{青(0%-100%)}}", "Mėlyna (0-100 %)"],
            ["{{青オフセット(-255〜255)}}", "Mėlynos spalvos poslinkis (nuo -255 iki 255)"],
            ["{{ブレンドモード}}", "maišymo režimas"],
            ["{{フィルターを選択}}", "Pasirinkite filtrą"],
            ["{{フィルターを追加}}", "Pridėti filtrą."],
            ["{{サウンドを追加}}", "Pridėkite garsą."],
            ["{{フィルターを表示・非表示する}}", "Rodyti / slėpti filtrus"],
            ["{{フィルターを削除}}", "Pašalinti filtrus."],
            ["{{水平方向にぼかす}}", "Horizontaliai išsklaidykite vaizdą."],
            ["{{垂直方向にぼかす}}", "Vertikalus suliejimas."],
            ["{{フィルター強度}}", "Filtro stiprumas"],
            ["{{フィルター角度}}", "Filtro kampas"],
            ["{{シャドウのアルファ}}", "Šešėlių Alfa."],
            ["{{シャドウのカラー}}", "Šešėlių spalvos."],
            ["{{フィルター距離}}", "Atstumas iki filtro"],
            ["{{ハイライトのカラー}}", "Spalviniai akcentai"],
            ["{{ハイライトのアルファ}}", "Svarbiausias \"Alpha\"."],
            ["{{グラデーションカラー}}", "gradacijos spalva"],
            ["{{グラデーションのアルファ}}", "gradiento alfa"],
            ["{{タブの移動・名前を変更}}", "Skirtukų perkėlimas ir pervadinimas"],
            ["{{プロジェクトを閉じる}}", "Uždaryti projektą"],
            ["{{上下に移動}}", "Judėjimas aukštyn ir žemyn"],
            ["{{レイヤー変更(ダブルクリック)}}", "Sluoksnio keitimas (dukart spustelėkite)"],
            ["{{レイヤーをハイライト}}", "Paryškinti sluoksniai."],
            ["{{レイヤーを非表示}}", "Paslėpti sluoksnius."],
            ["{{レイヤーをロック}}", "Užrakto sluoksniai."],
            ["{{カーブポインター(ダブルクリックでON/OFF)}}", "Kreivinė rodyklė (dukart spustelėkite, kad įjungtumėte / išjungtumėte)"],
            ["{{インスタンス名}}", "egzemplioriaus pavadinimas"],
            ["{{ライブラリ内の検索}}", "Paieška bibliotekoje"],
            ["{{フレームラベル}}", "rėmo etiketė"],
            ["{{プロジェクトが保存されていない場合、このタブのプロジェクトデータを復旧する事はできません。タブを削除しますか？}}}}", "Jei projektas neišsaugotas, šio skirtuko projekto duomenų atkurti neįmanoma. Ar norite ištrinti skirtuką?}}"]
        ]);
    }
}
